<?xml version="1.0"?>

<robot name="caster_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 보조 바퀴 속성 정의 -->
  <xacro:property name="caster_wheel_radius" value="0.025" />  
  <xacro:property name="caster_wheel_height" value="0.015" /> 
  <xacro:property name="caster_wheel_mass" value="0.5" /> <!-- in kg--> 
  
  <xacro:property name="base_x_origin_to_caster_wheel_origin" value="0.25" /> 
  <xacro:property name="base_y_origin_to_caster_wheel_origin" value="0.0" /> 
  <xacro:property name="base_z_origin_to_caster_wheel_origin" value="0.0" />

  <!-- 보조 바퀴 매크로 정의 -->
  <xacro:macro name="caster_wheel" params="parent translateX translateY flipY">
    <link name="caster_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${flipY*M_PI/2} 0 0" />
        <geometry>
          <cylinder length="${caster_wheel_height}" radius="${caster_wheel_radius}" />
        </geometry>
        <material name="Black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${flipY*M_PI/2} 0 0" />
        <geometry>
          <cylinder length="${caster_wheel_height}" radius="${caster_wheel_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${caster_wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
      </inertial>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="caster_wheel"/>
      <origin xyz="${translateX} ${translateY} ${-(0.05 / 2 + caster_wheel_radius)}" rpy="0 0 0" />
    </joint>

    <!-- Gazebo 설정 -->
    <gazebo reference="caster_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

  </xacro:macro>

</robot>
